'use client';
import { useCallback, useEffect, useState } from 'react';
import { HeartHandshake, Plus, ListTodo, Clock3, CheckCheck, CalendarDays, ChevronLeft, ChevronRight, MapPin, Pencil, Trash2, X, LockKeyhole, Check, LoaderCircle, RefreshCw, Tag, Users, ShoppingCart } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from '@/components/ui/empty';
import { statuses, assignees as defaultAssignees, type Status, type Task } from '@/lib/task-types';
import { apiFetch as fetch } from '@/lib/api';
const icons = {active:ListTodo, future:Clock3, done:CheckCheck};
const blank = {title:'', details:'', topic:'', location:'', for_child:'family' as const, due:'', assignee:'together', status:'active' as Status};
type BoardPayload = { tasks:Task[]; user:string; local:boolean; members:Record<string,string>; error?:string };
function dateLabel(date:string, time=false) { return new Intl.DateTimeFormat('he-IL', {dateStyle:'medium', ...(time ? {timeStyle:'short' as const}:{}), timeZone:'Asia/Jerusalem'}).format(new Date(date.length===10 ? date+'T12:00:00':date)); }
export default function Board() {
 const [calendarMonth,setCalendarMonth]=useState(()=>new Date());
 const [calendarDay,setCalendarDay]=useState<string|null>(null);
 const [assignees,setAssignees]=useState(defaultAssignees);
 const [tasks,setTasks]=useState<Task[]>([]), [tab,setTab]=useState<Status>('active'), [loading,setLoading]=useState(true), [error,setError]=useState(''), [message,setMessage]=useState('');
 const [editor,setEditor]=useState(false), [editing,setEditing]=useState<Task|null>(null), [draft,setDraft]=useState(blank), [saving,setSaving]=useState(false), [deleting,setDeleting]=useState<Task|null>(null), [busy,setBusy]=useState<string|null>(null);
 const [user,setUser]=useState(''), [local,setLocal]=useState(false), [today,setToday]=useState(''), [formError,setFormError]=useState(''), [unauthorized,setUnauthorized]=useState(false);
 const load=useCallback(async()=>{try{const res=await fetch('/api/tasks',{cache:'no-store'}); if(res.status===401){setTasks([]);setUnauthorized(true);throw new Error('יש להתחבר כדי לפתוח את הלוח הפרטי.');} const data=await res.json() as BoardPayload;if(!res.ok)throw new Error(data.error||'לא הצלחנו לטעון את המשימות.');setTasks(data.tasks);setAssignees({...defaultAssignees,...data.members});setUser(data.user);setLocal(data.local);setError('');}catch(e){setError(e instanceof Error?e.message:'החיבור לא הצליח. נסו שוב.');}finally{setLoading(false);}},[]);
 useEffect(()=>{load();setToday(new Intl.DateTimeFormat('he-IL',{dateStyle:'full',timeZone:'Asia/Jerusalem'}).format(new Date()));const timer=setInterval(load,15000);const focus=()=>load();window.addEventListener('focus',focus);return()=>{clearInterval(timer);window.removeEventListener('focus',focus);};},[load]);

 const calendarYear=calendarMonth.getFullYear();
 const calendarMonthIndex=calendarMonth.getMonth();
 const monthName=new Intl.DateTimeFormat('he-IL',{month:'long',year:'numeric',timeZone:'Asia/Jerusalem'}).format(new Date(calendarYear,calendarMonthIndex,1,12));
 const daysInMonth=new Date(calendarYear,calendarMonthIndex+1,0).getDate();
 const firstWeekday=new Date(calendarYear,calendarMonthIndex,1,12).getDay();
 const calendarCells=Array.from({length:firstWeekday+daysInMonth},(_,i)=>i<firstWeekday?null:i-firstWeekday+1);
 const dateKey=(day:number)=>String(calendarYear)+'-'+String(calendarMonthIndex+1).padStart(2,'0')+'-'+String(day).padStart(2,'0');
 const currentDateKey=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date());
 const childLabels={family:'משפחה',sagi:'שגיא',maya:'מאיה',alma:'אלמה',liam:'ליאם'};
 const selectedDayTasks=calendarDay?tasks.filter(task=>task.due===calendarDay):[];
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(timer);},[message]);
 const openNew=()=>{setEditing(null);setDraft({...blank,status:tab==='done'?'active':tab});setFormError('');setEditor(true);};
 const openTask=(task:Task)=>{setEditing(task);setDraft({title:task.title,details:task.details,topic:task.topic,location:task.location||'',for_child:task.for_child||'family',due:task.due,assignee:task.assignee,status:task.status});setFormError('');setEditor(true);};
 async function mutate(method:string,body:unknown){const res=await fetch('/api/tasks',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json() as {error?:string;id?:string;ok?:boolean};if(!res.ok){if(res.status===409)await load();throw new Error(data.error||'השינוי לא נשמר. נסו שוב.');}await load();return data;}
 async function save(e:React.FormEvent){e.preventDefault();if(saving)return;setSaving(true);setFormError('');try{await mutate(editing?'PATCH':'POST',{...draft,...(editing?{id:editing.id,version:editing.version}:{})});setEditor(false);setTab(draft.status);setMessage(editing?'השינויים נשמרו':'המשימה נוספה ללוח');}catch(e){setFormError((e as Error).message);}finally{setSaving(false);}}
 async function toggle(task:Task){if(busy)return;setBusy(task.id);try{await mutate('PATCH',{...task,status:task.status==='done'?'active':'done'});setMessage(task.status==='done'?'המשימה חזרה למשימות':'עוד דבר מאחורינו! המשימה עברה לטופל');}catch(e){setError((e as Error).message);}finally{setBusy(null);}}
 async function remove(){if(!deleting||saving)return;setSaving(true);try{await mutate('DELETE',{id:deleting.id,version:deleting.version});setDeleting(null);setMessage('המשימה נמחקה');}catch(e){setError((e as Error).message);setDeleting(null);}finally{setSaving(false);}}
 return <div className="app-shell"><header className="masthead"><a className="brand" href="/" aria-label="ביחד, הלוח שלנו"><span className="brand-mark"><HeartHandshake size={25}/></span><strong>משפחת חלילי<span>.</span></strong></a><div className="header-end"><span className="private"><LockKeyhole size={14}/> מרחב פרטי</span><span className="avatar-pair" aria-label="הלוח הזוגי"><span>א</span><span>ש</span></span></div></header>
 <main className="workspace"><div className="intro"><div><p className="date-line"><CalendarDays size={15}/>{today||'הלוח המשותף שלנו'}</p><h1>הלוח שלנו<span>.</span></h1></div><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><a className="secondary" href="/shopping"><ShoppingCart size={20}/> רשימת קניות</a><button className="primary" onClick={openNew} disabled={unauthorized}><Plus size={20}/> הוספת משימה</button></div></div>

 <section className="calendar-card" aria-label="לוח שנה משפחתי"><div className="calendar-head"><div><span className="eyebrow">תכנון משפחתי</span><h2>היומן שלנו</h2></div><div className="calendar-nav"><button className="icon-button" onClick={()=>setCalendarMonth(new Date(calendarYear,calendarMonthIndex-1,1,12))} aria-label="חודש קודם"><ChevronRight size={18}/></button><strong>{monthName}</strong><button className="icon-button" onClick={()=>setCalendarMonth(new Date(calendarYear,calendarMonthIndex+1,1,12))} aria-label="חודש הבא"><ChevronLeft size={18}/></button></div></div><div className="calendar-weekdays">{['א׳','ב׳','ג׳','ד׳','ה׳','ו׳','ש׳'].map(day=><span key={day}>{day}</span>)}</div><div className="calendar-grid">{calendarCells.map((day,index)=>{const key=day?dateKey(day):'';const dayTasks=day?tasks.filter(task=>task.due===key):[];return day?<button key={index} className={'calendar-day '+(calendarDay===key?'selected ':'')+(currentDateKey===key?'today':'')} onClick={()=>setCalendarDay(key)}><span className="calendar-number">{day}</span>{dayTasks.length>0&&<span className="calendar-dots">{dayTasks.some(t=>t.assignee==='husband')&&<i className="dot dot-husband"/>}{dayTasks.some(t=>t.assignee==='wife')&&<i className="dot dot-wife"/>}{dayTasks.some(t=>t.assignee==='together')&&<i className="dot dot-together"/>}</span>}</button>:<span key={index} className="calendar-blank"/>;})}</div>{calendarDay&&<div className="day-popover"><div className="day-popover-head"><strong>{dateLabel(calendarDay)}</strong><button className="icon-button" onClick={()=>setCalendarDay(null)} aria-label="סגירת המשימות"><X size={16}/></button></div>{selectedDayTasks.length===0?<p>אין משימות לתאריך הזה.</p>:<div className="day-task-list">{selectedDayTasks.map(task=><div className="day-task" key={task.id}><i className={'dot dot-'+task.assignee}/><div><strong>{task.title}</strong><span>{assignees[task.assignee]} · {childLabels[task.for_child||'family']}</span></div></div>)}</div>}</div>}</section>
 <div className="summary-strip"><div className="summary-card"><strong>{tasks.filter(t=>t.assignee==='husband'&&t.status!=='done').length}</strong><span>משימות פתוחות לשגיא</span></div><div className="summary-card"><strong>{tasks.filter(t=>t.assignee==='wife'&&t.status!=='done').length}</strong><span>משימות פתוחות למאיה</span></div><div className="summary-card"><strong>{tasks.filter(t=>t.due===new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jerusalem'}).format(new Date())&&t.status!=='done').length}</strong><span>להיום</span></div><div className="summary-card"><strong>{tasks.filter(t=>{const d=t.due?new Date(t.due+'T12:00:00'):null;const end=new Date();end.setDate(end.getDate()+7);return d&&d>=new Date(new Date().toDateString())&&d<end&&t.status!=='done';}).length}</strong><span>לשבוע הקרוב</span></div></div>\n <div className="board-heading"><span><i className="live-dot"/>{user?`מחובר: ${user}`:'המרחב המשותף שלנו'}</span><span>{tasks.length?`${tasks.filter(t=>t.status==='done').length} מתוך ${tasks.length} משימות טופלו`:'מתחילים את הרשימה שלנו'}</span></div>
 <Tabs value={tab} onValueChange={v=>setTab(v as Status)} className="board-tabs"><TabsList className="inboxes" aria-label="תיבות המשימות">{(Object.keys(statuses) as Status[]).map(status=>{const Icon=icons[status];return <TabsTrigger key={status} value={status} className={`inbox inbox-${status}`}><span className="inbox-symbol"><Icon size={22}/></span><span className="inbox-name">{statuses[status]}</span><span className="inbox-count">{tasks.filter(t=>t.status===status).length}</span></TabsTrigger>;})}</TabsList>
 {error&&<div className="error-banner" role="alert"><span>{error}</span>{unauthorized?<a href="/">כניסה ללוח</a>:<button onClick={load}><RefreshCw size={16}/> ניסיון נוסף</button>}</div>}
 {(Object.keys(statuses) as Status[]).map(status=><TabsContent value={status} key={status} className="task-panel"><div className="list-heading"><h2>{statuses[status]}</h2><span>{status==='done'?'הדברים שכבר מאחורינו':status==='future'?'נחזור לזה בזמן המתאים':'הדברים שעל הפרק'}</span></div>
 {loading?<div className="loading" role="status"><LoaderCircle className="spin"/> טוענים את הלוח…</div>:!tasks.some(t=>t.status===status)?<Empty className="empty-state"><div className={`empty-icon empty-${status}`}>{status==='done'?<CheckCheck size={32}/>:status==='future'?<Clock3 size={32}/>:<ListTodo size={32}/>}</div><EmptyHeader><EmptyTitle>{status==='done'?'כאן יופיע כל מה שסיימנו':status==='future'?'אין משימות שמחכות להמשך':'יש מקום לדברים הבאים'}</EmptyTitle><EmptyDescription>{status==='done'?'סמנו ✓ ליד משימה שבוצעה והיא תעבור לכאן.':status==='future'?'תוכניות שעוד לא הגיע הזמן לטפל בהן יישמרו כאן.':'סידור קטן, תוכנית גדולה — נוסיף את המשימה הראשונה?'}</EmptyDescription></EmptyHeader>{status!=='done'&&<button className="secondary" onClick={openNew} disabled={unauthorized}><Plus size={18}/>{status==='future'?'הוספת משימה עתידית':'הוספת משימה ראשונה'}</button>}</Empty>:<div className="task-list">{tasks.filter(t=>t.status===status).map(task=><article className={`task-card ${status==='done'?'completed':''}`} key={task.id}><Checkbox className="task-check" checked={status==='done'} onCheckedChange={()=>toggle(task)} disabled={busy!==null} aria-label={status==='done'?`החזרת ${task.title} למשימות`:`סימון ${task.title} כטופל`}/><button className="task-main" onClick={()=>openTask(task)}><h3>{task.title}</h3>{task.details&&<p>{task.details}</p>}<div className="task-meta"><span className={`person person-${task.assignee}`}><Users size={13}/>{assignees[task.assignee]}</span>{task.topic&&<span><Tag size={13}/>{task.topic}</span>}{task.for_child&&task.for_child!=='family'&&<span className="child-badge">{task.for_child==='alma'?'אלמה':'ליאם'}</span>}{task.location&&<span><MapPin size={13}/>{task.location}</span>}{task.due&&<span><CalendarDays size={14}/>{dateLabel(task.due)}</span>}</div><span className="updated">עודכן על ידי {task.updated_by} · {dateLabel(task.updated_at,true)}</span></button><div className="task-actions"><button className="icon-button" aria-label={`עריכת ${task.title}`} onClick={()=>openTask(task)}><Pencil size={17}/></button><button className="icon-button danger" aria-label={`מחיקת ${task.title}`} onClick={()=>setDeleting(task)}><Trash2 size={17}/></button></div></article>)}</div>}</TabsContent>)}
 </Tabs><footer className="board-footer"><span><HeartHandshake size={16}/> הלוח של שנינו</span><span>{local?'תצוגה מקומית · נתונים נפרדים מהאתר':'המשימות משותפות לשני החשבונות'}</span></footer></main>
 <Dialog open={editor} onOpenChange={o=>{if(!saving)setEditor(o);}}><DialogContent className="task-dialog" showCloseButton={false} dir="rtl"><div className="modal-heading"><div><DialogTitle>{editing?'עריכת משימה':'משימה חדשה'}</DialogTitle><DialogDescription>{editing?'אפשר לשנות פרטים, להוסיף נושא או להעביר לתיבה אחרת.':'מה נרצה לקדם יחד?'}</DialogDescription></div><button className="icon-button" onClick={()=>setEditor(false)} disabled={saving} aria-label="סגירה"><X size={20}/></button></div>
 <form onSubmit={save}><label htmlFor="task-title">כותרת המשימה <span className="required">*</span></label><input id="task-title" autoFocus required maxLength={160} value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})} placeholder="למשל, לקבוע תור לרופא"/><label htmlFor="task-details">פרטים נוספים</label><textarea id="task-details" maxLength={10000} rows={4} value={draft.details} onChange={e=>setDraft({...draft,details:e.target.value})} placeholder="כל מה שכדאי שנזכור…"/>
 <div className="form-grid"><div><label htmlFor="task-location">מיקום (אופציונלי)</label><input id="task-location" maxLength={160} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})} placeholder="למשל, סופר או מרפאה"/></div><div><label htmlFor="task-topic">נושא</label><input id="task-topic" maxLength={80} value={draft.topic} onChange={e=>setDraft({...draft,topic:e.target.value})} placeholder="למשל, בית או משפחה"/></div><div><label htmlFor="task-due">מועד לביצוע</label><input type="date" id="task-due" value={draft.due} onChange={e=>setDraft({...draft,due:e.target.value})}/></div></div>
 <div className="form-grid"><div><label id="person-label">מי מטפל?</label><Select value={draft.assignee} onValueChange={v=>v&&setDraft({...draft,assignee:v})}><SelectTrigger aria-labelledby="person-label" className="form-select"><SelectValue>{assignees[draft.assignee]}</SelectValue></SelectTrigger><SelectContent dir="rtl">{Object.entries(assignees).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div><div><label id="child-label">עבור מי?</label><Select value={draft.for_child} onValueChange={v=>v&&setDraft({...draft,for_child:v as 'family'|'alma'|'liam'})}><SelectTrigger aria-labelledby="child-label" className="form-select"><SelectValue>{childLabels[draft.for_child]}</SelectValue></SelectTrigger><SelectContent dir="rtl"><SelectItem value="family">כל המשפחה</SelectItem><SelectItem value="sagi">שגיא</SelectItem><SelectItem value="maya">מאיה</SelectItem><SelectItem value="alma">אלמה</SelectItem><SelectItem value="liam">ליאם</SelectItem></SelectContent></Select></div><div><label id="status-label">תיבה</label><Select value={draft.status} onValueChange={v=>v&&setDraft({...draft,status:v as Status})}><SelectTrigger aria-labelledby="status-label" className="form-select"><SelectValue>{statuses[draft.status]}</SelectValue></SelectTrigger><SelectContent dir="rtl">{Object.entries(statuses).map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></div></div>
 {editing&&<div className="edit-stamp">עדכון אחרון: {editing.updated_by} · {dateLabel(editing.updated_at,true)}</div>}{formError&&<p className="form-error" role="alert">{formError}</p>}<div className="form-actions"><button className="primary" type="submit" disabled={saving||!draft.title.trim()}>{saving?<LoaderCircle className="spin" size={18}/>:<Check size={18}/>} {saving?'שומרים…':editing?'שמירת שינויים':'הוספת המשימה'}</button><button className="text-button" type="button" onClick={()=>setEditor(false)} disabled={saving}>ביטול</button></div></form></DialogContent></Dialog>
 <AlertDialog open={!!deleting} onOpenChange={o=>{if(!o&&!saving)setDeleting(null);}}><AlertDialogContent dir="rtl"><AlertDialogTitle>למחוק את המשימה?</AlertDialogTitle><AlertDialogDescription>המשימה „{deleting?.title}” וכל הפרטים שלה יימחקו. אם היא בוצעה, אפשר לסמן אותה כטופל במקום.</AlertDialogDescription><div className="confirm-actions"><AlertDialogAction onClick={remove} disabled={saving} className="delete-button">{saving?'מוחקים…':'מחיקת משימה'}</AlertDialogAction><AlertDialogCancel disabled={saving}>ביטול</AlertDialogCancel></div></AlertDialogContent></AlertDialog>
 {message&&<div className="toast" role="status"><CheckCheck size={19}/>{message}</div>}</div>;
}
